name: Run Apex Arc Engine

on:
  workflow_dispatch:  # Allows manual run from GitHub Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Prediction Engine
      run: |
        python main.py
